export const baseTheme = {
  id: "base",
  name: "Essencia Museum",
  colors: {
    background: "#140f0b",
    surface: "rgba(22, 16, 12, 0.82)",
    primary: "#d2a45f",
    secondary: "#704f35",
    accent: "#f0d7a1",
    text: "#f8ead0",
    mutedText: "#b9a88d",
    border: "rgba(210, 164, 95, 0.34)",
    glow: "#e8b765",
    danger: "#e36d6d",
  },
  hero: {
    fadeStart: 48,
    fadeEnd: 96,
    overlayOpacity: 0.2,
    vignetteOpacity: 0.72,
    saturation: 0.86,
    contrast: 1.08,
    brightness: 0.78,
  },
  frame: {
    style: "museum",
    thickness: 1,
    cornerSize: 18,
    opacity: 0.72,
    glowIntensity: 0.24,
  },
  texture: {
    type: "dark-paper",
    opacity: 0.22,
    blendMode: "soft-light",
  },
  particles: {
    type: "dust",
    amount: 22,
    speed: 0.28,
    size: 1,
    opacity: 0.42,
    reactsToAudio: true,
  },
  energy: {
    buttonStyle: "soft",
    intensity: 0.68,
    pulseDuration: 4.2,
    orbitingParticles: true,
    audioReactive: true,
  },
  waveform: {
    style: "cinematic",
    activeColor: "#e8b765",
    inactiveColor: "rgba(232, 183, 101, 0.22)",
    glowColor: "#f0d7a1",
    barWidth: 3,
    gap: 3,
    sensitivity: 0.62,
  },
  typography: {
    titleFamily: "var(--font-display, Georgia, serif)",
    bodyFamily: "var(--font-sans, Inter, sans-serif)",
    titleTransform: "none",
    titleLetterSpacing: "0.02em",
  },
  effects: {
    scanlines: false,
    scanlineOpacity: 0,
    filmGrain: true,
    filmGrainOpacity: 0.08,
    chromaticAberration: false,
    shimmer: true,
    parallax: true,
  },
};

